# Welcome to Jekyll!
#

# Site settings
title: janolivermr
description: |
  A curious mix of
  travel, development and home automation
owner: Jan Stolle # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: janolivermr@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://janolivermr.com" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title:output_ext

lang: en-us # used in HTML lang attributes

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Welcome 
  text: _My name is Jan and I'm a web developer, traveller and home automator._
# - displayed at the bottom
closing-head: 
closing-para: 

show_excerpts: true

social:
  #twitter: https://twitter.com/janolivermr
  github: https://github.com/janolivermr
  linkedin-square: https://www.linkedin.com/in/jan-stolle/
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/janolivermr
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
